### PR TITLE
Handle chunked stdout

### LINKED ISSUE #14: Reformatting file deletes most of the file's content
It requires a couple undo commands to recover the text. Using the latest 0.7.0 in Atom 1.32.2.

### PR DESCRIPTION
**Pull request by richardbann**
This fixes #14.

### CODE REVIEW

**Comment by svandecappelle** [comment]
Could you merge this to solve the #14 ?

**Comment by samwaterbury** [comment]
If this fixes #14, I'd like if it were merged. At the moment this plugin is completely unusable as it is liable to destroy source files. If @mikehoyio is not active on GitHub, we should fork this repository.

**Comment by richardbann** [comment]
@samwaterbury, feel free to fork it, let me know if I can help in any way.

**Comment by samwaterbury** [comment]
Hmm, on second thought I'm hesitant to fork since it would be nice to avoid duplicating the package in APM. I'm going to try to contact @mikehoyio to see if he can revisit this repository and ideally add another maintainer.

In the meantime, I realized you can install Atom packages from a repo! So a temporary workaround until this can get merged is:
```
apm install https://github.com/richardbann/atom-python-black.git
```

**Comment by richardbann** [comment]
@samwaterbury, atom-beautify (https://atom.io/packages/atom-beautify) works for us. What do you think?

**Pull request closed without merging**
